### ISSUE TITLE
Which Android Client?

### ISSUE THREAD

**Issue by essoojay** [noobz-id/noobzvpns#3]
Which is the android client for this server?

Thanks

**Comment by noobz-id** [comment]
please wait on google play.... its on reviewing stage 😁

**Comment by essoojay** [comment]
> please wait on google play.... its on reviewing stage 😁

please can i review for you?

2, can you make option for proxy alone, option to choose from VPN  or PROXY to externals like openvpn etc thanks

**Comment by noobz-id** [comment]
For android client, link is already in README.MD :)
